version: "2.1"

services:
  oracle-se:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - 1521:1521
    environment:
      ORACLE_SID: xe
      ORACLE_PDB: pdb
      ORACLE_PWD: password
    volumes:
      - ./app:/var/www/html
      - ./media:/var/www/html/images
  calculator-ws:
    image: ccamilorrivera/calculator-ws
    ports:
      - 8081:8081