version: "3.5"

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - 1521:1521
    environment:
      ORACLE_SID: xe
      ORACLE_PDB: pdb
      ORACLE_PWD: password
    volumes:
      - ./app:/var/www/html
      - ./media:/var/www/html/images
  #employee-ws:
  #  build: .
  #  ports:
  #   - "8080:8080"
  #  depends_on:
  #    oracle:
  #      condition: service_healthy
  calculator:
    image: ccamilorrivera/calculator-ws
    ports:
      - 8081:8081
